develop ci/cd fixes 3

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -6,28 +6,27 @@ on:
       - develop
 
 jobs:
-#test
+  # Job for static code analysis
   lint:
     runs-on: ubuntu-latest
-    name: Static Code Analysis with Flake8
     steps:
-      - name: Checkout Repository
+      - name: Checkout code
         uses: actions/checkout@v2
         
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: "3.9"
+          python-version: '3.8'
 
-      - name: Install Dependencies
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-          pip install flake8
+          pip install ruff flake8
 
-      - name: Run flake8
+      - name: Run static code analysis with Flake8
         run: |
-          flake8 . || echo "Linter failed but not blocking the pipeline" 
+          flake8 . || echo "Flake8 linter found issues, but they won't fail the pipeline."
 
   dependency_analysis:
     runs-on: ubuntu-latest
